# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: MyDefaultPool
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'My Docker Hub'
          repository: 'dropthebrat/weatherforecast'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'